### ISSUE TITLE
Setup Cohort Chat Channel

### ISSUE THREAD

**Issue by emmairwin** [maintainercohort/cohort-repo#10]
As per our conversation in the last call, setup a Telegram channel and share with the group.

**Comment by princiya** [comment]
_Deprecated. Please see the below comments for the latest telegram group info_

Here is the telegram channel https://t.me/joinchat/AAAAAFY1uxbLytEFmsVEWw

Please let me know if you have trouble joining in.

I am not sure if 'channel' is the right way. Maybe telegram 'group' is a better option? If yes, then I need atleast one of your telegram numbers ​🙂​, else I cannot create a group. You can write your number in the dropbox paper and let me know.

**Comment by princiya** [comment]
@emmairwin have you heard of Spectrum - https://spectrum.chat/

I was just playing around and I have setup a private community https://spectrum.chat/maidiv. If someone is interested, please join and we can evaluate if this is worth exploring.

P.S. Recently, Spectrum became part of Github!

**Comment by rkdotsreepriya** [comment]
Hey ,

 I have joined the channel. A super group will be a better option. My
telegram handle is @sreepriyark

See you there in telegram!

Regards,
Sreepriya

**Comment by princiya** [comment]
@sreepriyaRK thanks for joining the channel. I cannot yet create the 'group' just by your username because of the privacy settings in your account, looks like you have chosen to not let strangers randomly send you group invitations (which is the perfect setting to consider). Do you mind pinging me your number so that I can add you to my contacts and then I can create the 'group'.

**Comment by princiya** [comment]
thanks @ShaguftaMethwani for creating the group https://t.me/maintainercohort and saving me from the Telegram 'group' vs 'channel' mess ;)

**Comment by emmairwin** [comment]
yay!  Thank for your work
